export const DUMMY_DATA = [
  {
    product: "Titan Connected X",
    brand: "titan",
    type: "analog",
    straps: "leather",
    gender: "male",
    price: 11995,
  },
  {
    product: "Titan Urban Magic Blue",
    brand: "titan",
    type: "analog",
    straps: "metal",
    gender: "male",
    price: 1199,
  },
  {
    product: "C 22",
    brand: "casio",
    type: "digital",
    straps: "metal",
    gender: "female",
    price: 1299,
  },
  {
    product: "F 34",
    brand: "casio",
    type: "analog",
    straps: "metal",
    gender: "female",
    price: 1599,
  },
  {
    product: "Seiko R2",
    brand: "seiko",
    type: "analog",
    straps: "metal",
    gender: "male",
    price: 1799,
  },
  {
    product: "Seiko D12",
    brand: "seiko",
    type: "digital",
    straps: "leather",
    gender: "male",
    price: 1499,
  },
  {
    product: "Cartier White",
    brand: "cartier",
    type: "analog",
    straps: "metal",
    gender: "female",
    price: 1099,
  },
  {
    product: "Cartier SPlus",
    brand: "cartier",
    type: "analog",
    straps: "metal",
    gender: "male",
    price: 1799,
  },
  {
    product: "Rolex Sky-Dweller",
    brand: "rolex",
    type: "analog",
    straps: "leather",
    gender: "male",
    price: 1499,
  },
  {
    product: "Rolex GMT-Master II",
    brand: "rolex",
    type: "analog",
    straps: "metal",
    gender: "male",
    price: 5999,
  },
];
